version: '3'

services:
  atividade_nestjs:
    container_name: atividade_nestjs
    build: .
    command: /bin/sh -c "while sleep 1000; do :; done"
    ports:
      - 3333:3333
    networks:
      - app-network
    volumes:
      - ../:/boilerplate:cached

  atividade_postgres:
    container_name: atividade_postgres
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    networks:
      - app-network
    volumes:
      - ./.docker/pgdata:/var/lib/postgresql

  atividade_postgres_test:
    container_name: atividade_postgres_test
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5433:5432
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
